FROM python:3.8-slim

RUN mkdir -p /app
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ADD ./src ./src

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    build-essential \
    git-core

COPY ./setup.py ./
COPY ./requirements /app/requirements
RUN pip install -U pip && pip install -r requirements/dev.txt
